In [14]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.svm import SVC

from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler

iris =  sns.load_dataset('iris') #data load
X= iris.iloc[:,:4]
y = iris.iloc[:,-1]
print(y)

0         setosa
1         setosa
2         setosa
3         setosa
4         setosa
5         setosa
6         setosa
7         setosa
8         setosa
9         setosa
10        setosa
11        setosa
12        setosa
13        setosa
14        setosa
15        setosa
16        setosa
17        setosa
18        setosa
19        setosa
20        setosa
21        setosa
22        setosa
23        setosa
24        setosa
25        setosa
26        setosa
27        setosa
28        setosa
29        setosa
         ...
120    virginica
121    virginica
122    virginica
123    virginica
124    virginica
125    virginica
126    virginica
127    virginica
128    virginica
129    virginica
130    virginica
131    virginica
132    virginica
133    virginica
134    virginica
135    virginica
136    virginica
137    virginica
138    virginica
139    virginica
140    virginica
141    virginica
142    virginica
143    virginica
144    virginica
145    virginica
146    virginica
147    virginica
148    virginica
149    virginica
Name: species, Length: 150, dtype: object

In [15]:
scal = StandardScaler() #scaling
X = scal.fit_transform(X)

In [16]:
# One Versus Rest 
svm_1 = SVC(kernel ='rbf', gamma = 5, C = 100)
svm_2 = SVC(kernel ='rbf', gamma = 5, C = 100)
svm_3 = SVC(kernel ='rbf', gamma = 5, C = 100)

In [17]:
from sklearn.model_selection import train_test_split #데이터셋 분리
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=48)

In [18]:
y_train = pd.get_dummies(y_train) #one hot encoding / 변수를 컬럼으로 만들고 0또는 1로 만든다

In [19]:
y_train

     setosa  versicolor  virginica
110       0           0          1
69        0           1          0
148       0           0          1
39        1           0          0
53        0           1          0
103       0           0          1
127       0           0          1
78        0           1          0
38        1           0          0
99        0           1          0
79        0           1          0
71        0           1          0
111       0           0          1
149       0           0          1
84        0           1          0
121       0           0          1
117       0           0          1
5         1           0          0
40        1           0          0
125       0           0          1
44        1           0          0
75        0           1          0
24        1           0          0
48        1           0          0
10        1           0          0
101       0           0          1
29        1           0          0
139       0           0          1
9         1           0          0
106       0           0          1
..      ...         ...        ...
47        1           0          0
142       0           0          1
133       0           0          1
49        1           0          0
131       0           0          1
42        1           0          0
45        1           0          0
144       0           0          1
60        0           1          0
27        1           0          0
118       0           0          1
143       0           0          1
25        1           0          0
21        1           0          0
135       0           0          1
18        1           0          0
66        0           1          0
30        1           0          0
104       0           0          1
58        0           1          0
28        1           0          0
46        1           0          0
6         1           0          0
92        0           1          0
34        1           0          0
64        0           1          0
91        0           1          0
81        0           1          0
51        0           1          0
0         1           0          0

[120 rows x 3 columns]

In [20]:
svm_1.fit(X_train,y_train.iloc[:,0])
svm_2.fit(X_train,y_train.iloc[:,1])
svm_3.fit(X_train,y_train.iloc[:,2])

SVC(C=100, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma=5, kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [21]:
svm_model_1= svm_1.decision_function(X_test) #decision_function hyperplane과의 거리!

In [22]:
svm_model_2=svm_2.decision_function(X_test)

In [23]:
svm_model_3=svm_3.decision_function(X_test)

In [25]:
flower_name = ['setosa','vir','virgin']

In [26]:
flower_name[0]=svm_model_1

In [27]:
flower_name[1]=svm_model_2

In [28]:
flower_name[2]=svm_model_3

OvR : One-vs-the-Rest
K개의 클래스가 존재하는 경우, 각각의 클래스에 대해서 표본이 속하는지 (y=1), 속하지 않는지 (y=0)의 이진 분류 문제를 해결.

각 클래스가 얻은 조건부 확률 값을 더해서 이 값이 가장 큰 클래스를 선택

In [32]:
decision = np.array([[7,2,5],[5,1,8],[6,8,3]]) 
result = map(lambda x : flower_name[x], [np.argmax(decision[i]) for i in range(len(decision))])
print(list(result))

[array([-1.12470845, -0.86326953, -0.65281099, -0.50248821, -0.76284323,
       -0.87465573,  1.07709345, -0.99281647,  0.47441336, -0.99842743,
       -0.83989348,  0.15633457,  0.32871788, -0.97965464, -0.72385083,
       -0.92638376,  1.28322481, -0.56240455, -0.72719892, -0.99509775,
        0.43166724, -0.96451557, -0.82991366, -1.03020581, -0.75166835,
        1.13461335,  0.39943974, -1.04194106, -0.93376548, -1.06133798]), array([-1.26277651, -0.77964936, -0.40539105, -0.13070947,  0.02643314,
        0.57365649, -1.04443118,  0.88027844, -0.69605517, -0.99074328,
        0.52442024, -0.51171892, -0.61157919,  0.78148257, -0.75517707,
       -0.76905925, -1.16380018, -0.25333938, -0.0251979 ,  0.98843144,
       -0.67129528,  0.89577306, -0.30363489, -1.03647008,  0.31622662,
       -1.07758405, -0.65251719,  1.09632055,  0.85541707, -1.11042784]), array([ 1.36054602,  0.62859488,  0.0580828 , -0.36987093, -0.25686625,
       -0.79229874, -1.03195247, -0.87132049, -0.77957234,  0.99327762,
       -0.73309581, -0.64607768, -0.71843897, -0.80882458,  0.47748663,
        0.69953462, -1.11879121, -0.1870504 , -0.24458236, -0.99337352,
       -0.76149141, -0.96812018,  0.11310267,  1.06892719, -0.56749692,
       -1.05639624, -0.74817515, -1.0537858 , -0.89721836,  1.17126024])]